test_that("chromatogramInfo.AgilentExport works", {
  result <- chromatogramInfo.AgilentExport("+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "TIC")
  expect_equal(result[1,4], as.numeric(NA))
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("+ESI EIC(485.6975) Scan Frag=125.0V Data0001.d ")
  expect_equal(names(result), c('polarity','signal','scan','mz','MS',
                                'fragmentor','filename'))
  expect_equal(result[1,1], "+")
  expect_equal(result[1,2], "ESI")
  expect_equal(result[1,3], "EIC")
  expect_equal(as.character(result[1,4]), "485.6975")
  expect_equal(result[1,5], "Scan")
  expect_equal(result[1,6], 125)
  expect_equal(result[1,7], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("DAD1 - A:Sig=280.0,4.0  Ref=550.0,100.0 Data0001.d")
  expect_equal(names(result), c('signal','scan','wavelength','filename'))
  expect_equal(result[1,1], "DAD1")
  expect_equal(result[1,2], "A:Sig=280.0,4.0")
  expect_equal(as.character(result[1,3]), "280")
  expect_equal(result[1,4], "Data0001.d")
  result <- chromatogramInfo.AgilentExport("BinPump1 - A: Pressure Data0001.d")
  expect_equal(names(result), c('signal','scan','filename'))
  expect_equal(result[1,1], "BinPump1")
  expect_equal(result[1,2], "Pressure")
  expect_equal(result[1,3], "Data0001.d")
})

test_that("readChromatogram.AgilentExport.memory works", {
  demoFile <- fs::path_package("extdata", "Data0001.CSV", package = "readAgilent")
  result <- readLines(demoFile, n = 9092)
  result <- readChromatogram.AgilentExport.memory(result)()
  expect_equal(nrow(result$data), 9090)
  expect_equal(as.character(min(result$data$rt)), "3.042")
  expect_equal(as.character(max(result$data$rt)), "33.035")
  expect_equal(as.character(min(result$data$intensity)), "19197")
  expect_equal(as.character(max(result$data$intensity)), "151731744")
  expect_equal(result$info$source, "Agilent")
  expect_equal(result$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  result <- readLines(demoFile, n = 9092)
  result <- readChromatogram.AgilentExport.memory(result,
                                                  translateComment = chromatogramInfo.AgilentExport)()
  expect_equal(nrow(result$data), 9090)
  expect_equal(as.character(min(result$data$rt)), "3.042")
  expect_equal(as.character(max(result$data$rt)), "33.035")
  expect_equal(as.character(min(result$data$intensity)), "19197")
  expect_equal(as.character(max(result$data$intensity)), "151731744")
  expect_equal(result$info$source, "Agilent")
  expect_equal(result$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(result$info$polarity, "+")
  expect_equal(result$info$signal, "ESI")
  expect_equal(result$info$scan, "TIC")
  expect_equal(result$info$mz, as.numeric(NA))
  expect_equal(result$info$MS, "Scan")
  expect_equal(result$info$fragmentor, 125)
  expect_equal(result$info$filename, "Data0001.d")
})

test_that("readChromatogram.AgilentExport works", {
  demoFile <- fs::path_package("extdata", "Data0001.CSV", package = "readAgilent")
  result <- readChromatogram.AgilentExport(demoFile, translateComment = chromatogramInfo.AgilentExport)()
  expect_length(result, 9)
  infoResult <- purrr::map_df(result, ~as.data.frame(.x$info))
  expect_equal(dim(infoResult), c( 9, 10))
  expect_equal(colnames(infoResult), c('source', 'comment', 'polarity', 'signal',
                                       'scan', 'mz', 'MS', 'fragmentor', 'filename',
                                       'wavelength'))
  expect_equal(infoResult$scan , c('TIC', 'BPC', 'EIC', 'EIC', 'EIC',
                                   'C:Sig=214.0,4.0', 'TWC', 'Solvent Ratio B',
                                   'Pressure'))
  expect_equal(nrow(result[[1]]$data), 9090)
  expect_equal(as.character(min(result[[1]]$data$rt)), "3.042")
  expect_equal(as.character(max(result[[1]]$data$rt)), "33.035")
  expect_equal(as.character(min(result[[1]]$data$intensity)), "19197")
  expect_equal(as.character(max(result[[1]]$data$intensity)), "151731744")
  expect_equal(result[[1]]$info$source, "Agilent")
  expect_equal(result[[1]]$info$comment, "+ESI TIC Scan Frag=125.0V Data0001.d ")
  expect_equal(result[[1]]$info$polarity, "+")
  expect_equal(result[[1]]$info$signal, "ESI")
  expect_equal(result[[1]]$info$scan, "TIC")
  expect_equal(result[[1]]$info$mz, as.numeric(NA))
  expect_equal(result[[1]]$info$MS, "Scan")
  expect_equal(result[[1]]$info$fragmentor, 125)
  expect_equal(result[[1]]$info$filename, "Data0001.d")
  expect_equal(nrow(result[[3]]$data), 9090)
  expect_equal(as.character(min(result[[3]]$data$rt)), "3.042")
  expect_equal(as.character(max(result[[3]]$data$rt)), "33.035")
  expect_equal(as.character(min(result[[3]]$data$intensity)), "0")
  expect_equal(as.character(max(result[[3]]$data$intensity)), "37359")
  expect_equal(length(result[[3]]$info), 9)
  expect_equal(result[[3]]$info$source, "Agilent")
  expect_equal(result[[3]]$info$comment, "+ESI EIC(465.6025) Scan Frag=125.0V Data0001.d ")
  expect_equal(result[[3]]$info$polarity, "+")
  expect_equal(result[[3]]$info$signal, "ESI")
  expect_equal(result[[3]]$info$scan, "EIC")
  expect_equal(as.character(result[[3]]$info$mz), "465.6025")
  expect_equal(result[[3]]$info$MS, "Scan")
  expect_equal(result[[3]]$info$fragmentor, 125)
  expect_equal(result[[3]]$info$filename, "Data0001.d")
})

test_that("peakListInfo.AgilentExport works", {
  info <- "D:/MassHunter/Data/Ben/Data0001.d, +ESI TIC Scan Frag=125.0V Data0001.d "
  result <- peakListInfo.AgilentExport(info)
  expect_equal(class(result),"data.frame")
  expect_equal(dim(result), c(1,8))
  expect_equal(colnames(result), c('polarity','signal','scan','mz','MS',
                                   'fragmentor','filename','location'))
  expect_equal(result$polarity, "+")
  expect_equal(result$signal, "ESI")
  expect_equal(result$scan, "TIC")
  expect_equal(is.na(result$mz), TRUE)
  expect_equal(as.character(result$fragmentor), "125")
  expect_equal(result$filename, "Data0001.d")
  expect_equal(result$location, "D:/MassHunter/Data/Ben/Data0001.d")
  info <- "D:/MassHunter/Data/Ben/Data0001.d, +ESI EIC(591.2807) Scan Frag=125.0V Data0001.d "
  result <- peakListInfo.AgilentExport(info)
  expect_equal(class(result),"data.frame")
  expect_equal(dim(result), c(1,8))
  expect_equal(colnames(result), c('polarity','signal','scan','mz','MS',
                                   'fragmentor','filename','location'))
  expect_equal(result$polarity, "+")
  expect_equal(result$signal, "ESI")
  expect_equal(result$scan, "EIC")
  expect_equal(as.character(result$mz), "591.2807")
  expect_equal(as.character(result$fragmentor), "125")
  expect_equal(result$filename, "Data0001.d")
  expect_equal(result$location, "D:/MassHunter/Data/Ben/Data0001.d")
})

test_that("readPeaklist.AgilentExport.memory works", {
  demoFile <- fs::path_package("extdata", "Data0001_MS.csv", package = "readAgilent")
  result <- readLines(demoFile)
  result <- readPeaklist.AgilentExport.memory(result, startsString = "Data0001")()
  expect_length(result, 2)
  expect_length(result$data, 5)
  expect_equal(dim(result$info), c(5, 10))
  expect_equal(colnames(result$info),
               c('polarity','signal','scan','mz','MS', 'fragmentor','filename',
                 'location', 'start', 'end'))
  expect_equal(result$info$scan, c("TIC", "BPC", "EIC", "EIC", "EIC"))
  expect_equal(result$info$start, c(2, 4, 6, 11, 16))
  expect_equal(result$info$end, c(2, 4, 9, 14, 23))
  expect_equal(result$data[[1]], NA)
  expect_equal(dim(result$data[[5]]), c(6, 38))
  expect_equal(result$data[[5]]$Peak, 1:6)
  expect_equal(as.character(sum(result$data[[5]]$Start)), "59.853")
  expect_equal(as.character(sum(result$data[[5]]$RT)), "60.283")
  expect_equal(as.character(sum(result$data[[5]]$End)), "61.418")
  expect_equal(as.character(sum(result$data[[5]]$Area)), "808533.02")
  expect_equal(as.character(sum(result$data[[5]]$Height)), "151619")
  demoFile <- fs::path_package("extdata", "Data0001_UV.csv", package = "readAgilent")
  result <- readLines(demoFile)
  result <- readPeaklist.AgilentExport.memory(result, startsString = "Data0001")()
  expect_length(result, 2)
  expect_length(result$data, 2)
  expect_equal(dim(result$info), c(2, 7))
  expect_equal(colnames(result$info),
               c('signal','scan','wavelength',
                 'filename','location', 'start', 'end'))
  expect_equal(result$info$scan, c("C:Sig=214.0","TWC"))
  expect_equal(result$data[[1]], NA)
  expect_equal(result$data[[2]], NA)
})

test_that("readPeaklist.AgilentExport.memory works", {
  demoFile <- fs::path_package("extdata", "Data0001_MS.csv", package = "readAgilent")
  result <- readPeaklist.AgilentExport(demoFile, startsString = "Data0001")()
  expect_length(result, 5)
  expect_equal(dim(result[[1]]$info), c(1, 10))
  expect_equal(colnames(result[[1]]$info),
               c('polarity','signal','scan','mz','MS', 'fragmentor','filename',
                 'location', 'start', 'end'))
  expect_equal(result[[1]]$info$scan, "TIC")
  expect_equal(result[[3]]$info$scan, "EIC")
  expect_equal(result[[1]]$info$start, 2)
  expect_equal(result[[3]]$info$start, 6)
  expect_equal(result[[1]]$info$end, 2)
  expect_equal(result[[3]]$info$end, 9)
  expect_equal(result[[1]]$data, NA)
  expect_equal(dim(result[[5]]$data), c(6, 38))
  expect_equal(result[[5]]$data$Peak, 1:6)
  expect_equal(as.character(sum(result[[5]]$data$Start)), "59.853")
  expect_equal(as.character(sum(result[[5]]$data$RT)), "60.283")
  expect_equal(as.character(sum(result[[5]]$data$End)), "61.418")
  expect_equal(as.character(sum(result[[5]]$data$Area)), "808533.02")
  expect_equal(as.character(sum(result[[5]]$data$Height)), "151619")
  demoFile <- fs::path_package("extdata", "Data0001_UV.csv", package = "readAgilent")
  result <- readPeaklist.AgilentExport(demoFile, startsString = "Data0001")()
  expect_length(result, 2)
  expect_equal(dim(result[[1]]$info), c(1, 7))
  expect_equal(colnames(result[[1]]$info),
               c('signal','scan','wavelength',
                 'filename','location', 'start', 'end'))
  expect_equal(result[[1]]$info$scan, "C:Sig=214.0")
  expect_equal(result[[2]]$info$scan, "TWC")
  expect_equal(result[[1]]$data, NA)
  expect_equal(result[[2]]$data, NA)
})



